
# this is the directory for processing
# the cropped images will be placed here as well
#path = "/home/cesare/Desktop/crystal/crystalImages/20192102/"

#minXY = 45
#maxXY = 700

cropImage <- function(imageName,saveName,minXY=45,maxXY=700){
	if(!require("imager",character.only = TRUE)){
		install.packages("imager")
		load("imager")
	}

	print(imageName)
	#rename for saving
	#mainImgName <- strsplit(basename(imageName),"\\.")[[1]][1]
	mainImgName <- basename(imageName)
	mainImgName <- substr(mainImgName, 0, nchar(mainImgName)-4)
	mainImgName = gsub("\\.","-",gsub("/","_",mainImgName))
 
 
	image = load.image(imageName)
	#seperate colors to crop on each seperate
	channels = list(R(image),G(image),B(image))
	#isolate background/letters from images
	background = (parmin(channels)==1) | fill(parmax(channels)==0,3)
 
	# for when we assign each distince image a number to mark it as unique
	# Ensure the 0 label is the biggest by setting the edges all equal
	background[,1,,] = T
	background[1,,,] = T
	background[,dim(background)[2],,] = T
	background[dim(background)[1],,,] = T
 
	# grab each continuous space seperated from eachother by the background while ignoring
	# distrotions generated by letters
	blobs = label(label(background,high_connectivity = F) == 0,high_connectivity = F)
	# ignore background label so that we dont just crop out the whole image
	frames = sort(unique(blobs))[-1]
 
	# for each unique labeled region find the min and max for the coordinates
	# it belongs to
	for(frame in frames)
	{try({
		print(frame)
		blobCoordinates <- get.locations(blobs,function(x)x==frame)-1
	 
		xSpan <- c(min(blobCoordinates$x)+1,
				 max(blobCoordinates$x)-1)
		ySpan <- c(min(blobCoordinates$y)+1,
				 max(blobCoordinates$y)-1)
		#print(frame)
		# make sure the region is big enough to be a picture
		if(diff(xSpan) > minXY && diff(ySpan) > minXY &&
		diff(xSpan) < maxXY && diff(ySpan) < maxXY){
			crop = as.cimg(image[max(xSpan[1],1):min(xSpan[2],width(image)),max(ySpan[1],1):min(ySpan[2],height(image)),,3])
			save.image(suppressWarnings(crop),file=file.path(saveName, paste0(mainImgName,"_",frame,".png")),1.0)
			#file=file.path(paste0(saveDir,"cutImages"), paste0(mainImgName,"_",frame,".png"))
			unlink( list.files(dirname(tempdir()), pattern = "\\.PPM$|\\.ppm$", full.names = T) )
			gc()
		}
	})}
}

cropDirectory <- function(searchDirectory,
						saveDirectory,
						minXY=45,
						maxXY=700,
						includeSubDir=T,
						mimicDirStructure=T){
	# dirStruct <- strsplit(imgName,searchDirectory)
	queryImgs <- list.files(searchDirectory, 
						pattern = "\\.JPG$|\\.jpg$|\\.PNG$|\\.png$", 
						full.names = T, 
						recursive = includeSubDir)
	completeImgs <- list.files(saveDirectory, 
							pattern = "\\.JPG$|\\.jpg$|\\.PNG$|\\.png$", 
							full.names = F, 
							recursive = T)
	
	mainImgName <- lapply(queryImgs, function(imageName){strsplit(basename(imageName),"/.")[[1]][1]})
	mainImgName <- lapply(mainImgName, function(imageName){strsplit(basename(imageName),"\\.JPG$|\\.jpg$|\\.PNG$|\\.png$")[[1]]})
	cropedImgNames <- lapply(completeImgs, function(imageName){strsplit(basename(imageName),"_")[[1]][1]})
	
	index <- !(mainImgName %in% cropedImgNames)
	withProgress(message = 'Cropping', value = 0,{
		progressTicker <- 0
		for(imgName in queryImgs[index]){
			progressTicker <- progressTicker+1
			if(mimicDirStructure){
				dirStruct <- gsub(searchDirectory,"",imgName,fixed=T)
				
				folderNames <- unlist(strsplit(dirStruct,"/"))
				folderNames <- folderNames[-length(folderNames)]
				folderNames <- folderNames[-which(folderNames %in% c("","\\") )]
				# is this even right?
				#folderNames <- folderNames[-which(folderNames %in% unlist(strsplit(saveDirectory,"/")) )]
				
				newDirStruct <- ""
				for(folder in folderNames){
					newDirStruct <- file.path(newDirStruct,folder)
					dir.create(file.path(saveDirectory,newDirStruct), showWarnings = FALSE)
				}
			}else{
				newDirStruct <- ""
			}
			print("==== + ====")
			print(basename(imgName))

			try(cropImage(imageName=imgName,
						 saveName=file.path(sub('/$','',saveDirectory),sub('^/','',newDirStruct)),
						 minXY=minXY,
						 maxXY=maxXY))
			incProgress(1/sum(index), detail = paste(basename(imgName)," -- ",progressTicker,"of",sum(index)))
		}
	})
}
